//Supports language addition
lang = {
    libs :
	[
	"ifBrowserLang:en", //English by porog
			"Name",
			"Initial HP number",
			"Final HP number",
			"Initial PP number",
			"Final PP number",
			"GENERATE",
			"Download GIF",
			"Successfully generated",
			"Name has invalid letter",
			"Enter a number",
			"Number must be less than 4 digits",
			"Style",
			"Programmed by [v]",
			//status
			"Status effect:",
			"None",
			"Asleep",
			"Cold",
			"Crying",
			"Diamondized",
			"Mushroomized",
			"Nausea",
			"Paralyzed",
			"Poisoned",
			"Possessed",
			"Solidified",
			"Sunstroke",
	"ifBrowserLang:es", //Spanish by porog
			"Nombre",
			"Número de PV inicial",
			"Número de PV final",
			"Número de PP inicial",
			"Número de PP final",
			"GENERAR",
			"Descargar GIF",
			"Generado exitosamente",
			"Nombre tiene letra inválida",
			"Introduce un número",
			"Número debe ser de menos de 4 dígitos",
			"Estilo",
			"Programado por [v]",
			//status
			"Efecto de estado:",
			"Ninguno",
			"Dormido",
			"Resfriado",
			"Llorando",
			"Diamonizado",
			"Honguizado",
			"Náusea",
			"Paralizado",
			"Envenenado",
			"Poseído",
			"Solidificado",
			"Insolación",
	"ifBrowserLang:ja", //Japanese by porog
			"名前",
			"HPの初期値",
			"HPの最終値",
			"PPの初期値",
			"PPの最終値",
			"生成する",
			"GIFをダウンロード",
			"生成完了",
			"名に無効な文字が含まれています",
			"数字を入力してください",
			"4桁以内の数値にしてください。",
			"スタイル",
			"[v]によって作成されました",
			//status
			"Status effect:",
			"None",
			"Asleep",
			"Cold",
			"Crying",
			"Diamondized",
			"Mushroomized",
			"Nausea",
			"Paralyzed",
			"Poisoned",
			"Possessed",
			"Solidified",
			"Sunstroke",
	""
	]
};